### ISSUE TITLE
Broken ?

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [synacktiv/gh-hijack-runner#1]
I made a Dockerfile

```
FROM python:3.12
ADD . /
RUN pip install -r requirements.txt
```

```
$  docker build -t hijack .
$ docker run -ti --rm hijack python3  gh-hijack-runner.py --registration-token $(curl -L -X POST -H "Authorization: Bearer PAT" https://api.github.com/orgs/TESTORG/actions/runners/registration-token|jq -r .token) --url https://github.com/TESTORG
```

I get
> [+] Session ID: 6b0e657c-507c-4057-898f-3e7008b893d2
[+] AES key: ExoOW....fg==

But nothing else the runner is register, but when I try a workflow using the label is does not start...

> Requested labels: self-hosted
Job defined at: TESTORG/TESTREPO/.github/workflows/x.yml@refs/heads/main
Waiting for a runner to pick up this job...

**Comment by hugo-syn** [comment]
Hi @fproulx-boostsecurity I think that GitHub introduced a new security feature preventing by default to use self-hosted runners define at the organization level on public repositories. You can make it work by enabling the 
`Allow public repositories`  option in org settings -> runner-groups -> Default -> Repository access. I tried in my org if you configure the runner at the repo level you don't need this option. Tell me if it works for you :)

**Comment by fproulx-boostsecurity** [comment]
Thanks @hugo-syn , I had a reason to try it. And I got it to dump the tokens, so looks like it works :)
